name: run test and build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: test
        run: make test
        shell: bash

      - name: test-coverage
        run:   ${{ github.workspace }}/update-sonarqube.sh
        shell: bash

      - name: build
        run: make build
        shell: bash
