name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2


      - name: test
        run: make test
        shell: bash

      - name: build
        run: make build
        shell: bash
